### ISSUE TITLE
Unable to activate bitfinex-rb-0.0.11, because faraday-0.11.0 conflicts with faraday

### ISSUE THREAD

**Issue by zdavatz** [bitfinexcom/bitfinex-api-rb#28]
Hi

I am doing
```
~/.software/bitfinex-api-rb/lib> ruby bitfinex-api-rb.rb 
```
and I get
```
/home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate bitfinex-rb-0.0.11, because faraday-0.11.0 conflicts with faraday (>= 0.9.2, ~> 0.9.2), json-2.0.2 conflicts with json (>= 1.8.3, ~> 1.8.3) (Gem::ConflictError)
        from /home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1408:in `activate'
        from /home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
        from /home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
        from /home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /home/zeno/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/zeno/.software/bitfinex-api-rb/lib/bitfinex.rb:7:in `<top (required)>'
        from bitfinex-api-rb.rb:1:in `require_relative'
        from bitfinex-api-rb.rb:1:in `<main>'
```

**Comment by erubboli-bfx** [comment]
Have you tried with `bundle exec` ? it should solve the conflicts for you. 

You should import the gem in your own script, there's an example you can run:
`bundle exec ruby example/ticker.rb`

**Comment by zdavatz** [comment]
Thanks. Doing that now.
