### ISSUE TITLE
cannot order with a very low price

### ISSUE THREAD

**Issue by ThomasPr** [bitfinexcom/bitfinex-api-rb#39]
If I set the price to a value below 0.0001, I get an error for a new order request. Take a look at the example with a price of 0.00009 (four zeros):

```
2.4.0 :011 >  @client.new_order("IOTBTC", 1, "exchange limit", "buy", 0.00009)
Bitfinex::BadRequestError: Key price should be a decimal number, e.g. "123.456"
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/bitfinex-rb-0.0.11/lib/bitfinex/errors.rb:20:in `on_complete'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/bitfinex-rb-0.0.11/lib/bitfinex/authenticated_rest.rb:9:in `authenticated_post'
        from /home/trading/.rvm/gems/ruby-2.4.0/gems/bitfinex-rb-0.0.11/lib/bitfinex/orders.rb:32:in `new_order'
        from (irb):11
        from /home/trading/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<main>'
```

But it works quite well with a price of 0.0001 (three zeros)
```
2.4.0 :012 >  @client.new_order("IOTBTC", 1, "exchange limit", "buy", 0.0001)
 => {"id"=>3029486428, "cid"=>56856233060, "cid_date"=>"2017-07-11", "gid"=>nil, "symbol"=>"iotbtc", "exchange"=>"bitfinex", "price"=>"0.0001", "avg_execution_price"=>"0.0", "side"=>"buy", "type"=>"exchange limit", "timestamp"=>"1499788056.336560589", "is_live"=>true, "is_cancelled"=>false, "is_hidden"=>false, "oco_order"=>nil, "was_forced"=>false, "original_amount"=>"1.0", "remaining_amount"=>"1.0", "executed_amount"=>"0.0", "src"=>"api", "order_id"=>3029486428}
```

**Comment by arvicco** [comment]
I think it's related to a library bug that I fixed here: https://github.com/bitfinexcom/bitfinex-api-rb/pull/36

It was merged into master, but I'm not sure if the fix made it to release yet.

**Comment by ThomasPr** [comment]
Jup, #36 fixes the issue. Thanks for your help!
