### ISSUE TITLE
Bitfinex::NotFoundError on api v2 trades

### ISSUE THREAD

**Issue by masterkain** [bitfinexcom/bitfinex-api-rb#65]
```
require 'bitfinex-rb'


Bitfinex::Client.configure do |conf|
  conf.api_key = 'key' # replace
  conf.secret = 'secret' # replace
  conf.use_api_v2
end

client = Bitfinex::Client.new
client.trades

Traceback (most recent call last):
       11: from /Users/kain/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       10: from (irb):14
        9: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/bitfinex-rb-0.1.0/lib/bitfinex/v2/trading.rb:65:in `trades'
        8: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/bitfinex-rb-0.1.0/lib/bitfinex/connection.rb:8:in `get'
        7: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
        6: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        5: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        4: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
        3: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        2: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
        1: from /Users/kain/.rvm/gems/ruby-2.5.0/gems/bitfinex-rb-0.1.0/lib/bitfinex/errors.rb:27:in `on_complete'
Bitfinex::NotFoundError (Bitfinex::NotFoundError)

```

**Comment by f3rno** [comment]
I'm closing this as it is outdated, the repo has been (mostly) completely rewritten.
